admWeb/src/main/java/com/youjitech/system/menu/vo/Menu.java
package com.youjitech.system.menu.vo;

import com.google.common.collect.Lists;
import lombok.Data;

import java.io.Serializable;
import java.util.List;
import java.util.Map;

/**
 * Created By wangbo
 * 2019/1/16
 */
@Data
public class Menu implements Serializable {

    public Menu(Integer idx, String name, String url, String menuIcon, String identity, Integer menuLevel, Map<String, String> menuNames) {
        super();
        this.idx = idx;
        this.name = name;
        this.url = url;
        this.menuIcon = menuIcon;
        this.identity = identity;
        this.menuLevel = menuLevel;
        this.menuNames = menuNames;
    }

    private Integer idx;
    private String name;
    private String url;
    private String menuIcon;
    private String identity;
    private Integer menuLevel;
    private List<Menu> children;
    private Map<String, String> menuNames;

    public List<Menu> getChildren() {
        if (children == null) {
            children = Lists.newArrayList();
        }
        return children;
    }

    public boolean isHasChildren() {
        return !getChildren().isEmpty();
    }
}

admWeb/src/main/webapp/WEB-INF/layouts/default.jsp
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sitemesh" uri="http://www.opensymphony.com/sitemesh/decorator" %>
<%@ taglib prefix="shiro" uri="http://shiro.apache.org/tags" %>
<c:set var="ctx" value="${pageContext.request.contextPath}"/>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>

    <title>天天陪练-机构管理系统</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta http-equiv="Cache-Control" content="no-store"/>
    <meta http-equiv="Pragma" content="no-cache"/>
    <meta http-equiv="Expires" content="0"/>
    <sitemesh:head/>
    <link rel="shortcut icon" href="${ ctx }/static/images/favicon.ico">
    <link href="${ ctx }/static/css/default.css" rel="stylesheet" type="text/css"/>
    <link href="${ ctx }/static/css/framework.css" rel="stylesheet" type="text/css"/>
    <link href="${ ctx }/static/js/easy.ui/themes/gray/easyui.css" rel="stylesheet" type="text/css"/>
    <link href="${ ctx }/static/js/easy.ui/themes/icon.css" rel="stylesheet" type="text/css"/>

    <script type="text/javascript" src="${ ctx }/static/js/easy.ui/jquery.js"></script>
    <%--<script type="text/javascript" src="${ ctx }/static/js/easy.ui/jquery.min.js"></script>--%>
    <script type="text/javascript" src="${ ctx }/static/js/easy.ui/jquery.easyui.min.js"></script>
    <script type="text/javascript" src="${ ctx }/static/js/easy.ui/locale/easyui-lang-${lang}.js"></script>
    <script type="text/javascript" src="${ ctx }/static/js/base/base-js.js"></script>
    <script type="text/javascript" src="${ ctx }/static/js/jquery.serializeJSON/jquery.serializeJSON.js"></script>
    <script type="text/javascript" src="${ ctx }/static/js/base/baseValidate.js"></script>
    <script type="text/javascript" src="${ ctx }/static/js/base/baseMessageBox.js"></script>
    <script type="text/javascript" src="${ ctx }/static/js/base/baseEasyui.js"></script>
    <script type="text/javascript" src="${ ctx }/static/js/base/default.js"></script>
    <script type="text/javascript" src="${ ctx }/static/js/template/template-web.js"></script>

    <script>
        !function (global) {
            global.baseUrl = '${ctx}';
            <%--global.amCode = '<shiro:principal property="amCode" />';--%>
            global.lang = '${lang}';

            //禁止页面右键
            $(document).bind("contextmenu",function(e){
                return false;
            });
        }(window);
    </script>
</head>
<body  class="easyui-layout" style="overflow: auto;">
<%@ include file="/WEB-INF/layouts/header.jsp" %>
<sitemesh:body/>
<%@ include file="/WEB-INF/layouts/footer.jsp" %>
</body>

</html>

admWeb/src/main/webapp/WEB-INF/layouts/footer.jsp
<%@ page language="java" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

admWeb/src/main/webapp/WEB-INF/layouts/header.jsp
<%@ page language="java" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<c:set var="ctx" value="${pageContext.request.contextPath}"/> 
<%@ taglib prefix="shiro" uri="http://shiro.apache.org/tags"%>

admWeb/src/main/webapp/WEB-INF/layouts/left.jsp
<%@ page language="java" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="shiro" uri="http://shiro.apache.org/tags" %>
<%@  taglib  uri="http://java.sun.com/jsp/jstl/functions"   prefix="fn" %>
<!-- BEGIN SIDEBAR -->
		<div class="page-sidebar nav-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->        
			<ul class="page-sidebar-menu" id="menu-sidebar">
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
<script id="menu-list" type="text/html">
<li>
<div class="sidebar-toggler hidden-phone"></div>
</li>
<li>
<i>&nbsp;</i>
</li>
<li>
<a href="{{baseUrl}}/index">
<i class="icon-home"></i> 
<span class="title">首页</span>
</a>
</li>
{{each menuList as menu i}}  
<li class="{{if activeMenuName == menu.identity}}active open{{/if}}">
	<!-- 一级菜单 -->
	<a class="active" href="javascript:;">
	<i class="{{ menu.menuIcon  ? menu.menuIcon :　'icon-sitemap' }}"></i> 
	<span class="title">{{ menu.name }}</span>
	<span class="arrow {{if menu.hasChildren && activeMenuName == menu.identity}}open{{/if}}"></span>
	</a>	
	{{if menu.children}}
		<ul class="sub-menu">
			{{each menu.children as subMenu i}}
				<li {{if secondActiveMenuName == subMenu.identity}} class="active" {{/if}}>
					{{if subMenu.url}}
						<a href="{{baseUrl}}{{subMenu.url}}">
					{{else}}
						<a href="javascript:;">
					{{/if}}
					{{ subMenu.name }}
					<span class="{{if subMenu.hasChildren}}arrow {{/if}}{{if secondActiveMenuName == subMenu.identity}}open{{/if}}"></span>
					</a>
					{{if subMenu.hasChildren}}
						<ul class="sub-menu">
						{{each subMenu.children as thirdMenu t}}
								<li {{if thirdActiveMenuName == thirdMenu.identity}}class="active"{{/if}}><a href="{{baseUrl}}{{thirdMenu.url}}">{{thirdMenu.name}}</a></li>
							{{/each}}
						</ul>
					{{/if}}
				</li>
			{{/each}}
		</ul>
	{{/if}}	
</li>	
{{/each}}	
</script>			
<script type="text/javascript">
//加载菜单
$(document).ready(function(){
	$.ajax({
		url : '${ctx}/menu/init',
		contentType : 'application/json',
		dataType : "json",
		type : "GET",
		success : function(data) {
			var activeMenuName = '${SECOND_MENU_STATUA_KEY}';
			var secondActiveMenuName = '${THIRD_MENU_STATUA_KEY}';
			var thirdActiveMenuName = '${FOURTH_MENU_STATUA_KEY}';
			var menuData = {
				menuList : data,
				activeMenuName : activeMenuName,
				secondActiveMenuName : secondActiveMenuName,
				thirdActiveMenuName : thirdActiveMenuName,
				baseUrl : baseUrl
			};
			var html = template('menu-list', menuData);
			$('#menu-sidebar').html(html);
		}
	});
});
</script>		

	
			